import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './brand.css'

const Icon = ({ children }) => <span className="icon" aria-hidden="true">{children}</span>
const plans = [
  { name: 'Mensal', price: '19,90', note: 'Liberdade para renovar quando quiser.' },
  { name: 'Trimestral', price: '54,90', note: 'Mais tempo para curtir sem preocupação.', featured: true },
  { name: 'Anual', price: '199,90', note: 'A melhor escolha para o ano inteiro.' }
]

function Brand() { return <a className="brand" href="/" aria-label="MyTV"><img src="/assets/mytv-logo.png" alt="MyTV" /></a> }

function Header({ portal, setPortal }) {
  return <header className="topbar"><Brand /><nav><a href="#recursos">Recursos</a><a href="#esportes">Esportes</a><a href="#planos">Planos</a></nav><button className="outline" onClick={() => setPortal(!portal)}>{portal ? 'Voltar ao site' : 'Minha conta'} <span>↗</span></button></header>
}

function LiveMock() {
  return <div className="tv-mock"><div className="tv-nav"><Brand /><span>⌕</span><span>♡</span><span className="avatar">A</span></div><div className="screen-art"><div className="live-pill">● AO VIVO</div><div className="screen-copy"><small>EXPERIÊNCIA MYTV</small><h3>Tudo o que você gosta.<br />Em uma única tela.</h3><p>TV ao vivo, filmes, séries e eventos esportivos.</p><button>Assistir agora <b>→</b></button></div></div><div className="mini-row"><div><span className="mini-icon">◉</span><p><b>Programação atual</b><small>Saiba o que está passando</small></p></div><div><span className="mini-icon">⚽</span><p><b>Esportes ao vivo</b><small>Jogos e eventos do dia</small></p></div></div></div>
}

function Landing({ setPortal }) {
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow">MYTV · DO SEU JEITO</p><h1>Uma TV completa.<br /><em>Uma experiência só sua.</em></h1><p className="lead">Canais ao vivo, filmes, séries e esportes em uma experiência rápida, elegante e feita para a sua TV.</p><div className="hero-actions"><button className="primary" onClick={() => document.querySelector('#planos').scrollIntoView({ behavior: 'smooth' })}>Começar agora <span>→</span></button><button className="text-button" onClick={() => document.querySelector('#recursos').scrollIntoView({ behavior: 'smooth' })}>Conheça a MyTV <span>↓</span></button></div><div className="trust"><span>✦</span><p><b>Feito para TV</b><small>Experiência pensada para o controle remoto.</small></p></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><LiveMock /></div></section>
  <section id="recursos" className="features section"><div className="section-heading"><p className="eyebrow">TUDO EM UM SÓ LUGAR</p><h2>Mais conteúdo.<br />Menos complicação.</h2><p>A MyTV organiza tudo que você gosta em uma navegação simples e rápida.</p></div><div className="feature-grid"><article className="feature-card violet"><Icon>▣</Icon><h3>TV ao vivo</h3><p>Canais organizados por categoria, com programação atual e navegação instantânea.</p><span>Explorar canais →</span></article><article className="feature-card blue"><Icon>◉</Icon><h3>Filmes e séries</h3><p>Encontre algo novo ou continue exatamente de onde parou.</p><span>Ver catálogo →</span></article><article className="feature-card orange"><Icon>◈</Icon><h3>Esportes</h3><p>Partidas, campeonatos e várias opções de transmissão quando disponíveis.</p><span>Ver agenda →</span></article></div></section>
  <section id="esportes" className="sports section"><div className="sports-top"><div><p className="eyebrow">AGENDA EM DESTAQUE</p><h2>O jogo está<br /><em>na sua tela.</em></h2></div><button className="outline">Ver todos os eventos <span>→</span></button></div><div className="events"><article className="event-card football"><span className="live-pill">● AO VIVO</span><small>CAMPEONATO NACIONAL</small><div className="teams"><b>Atlético</b><strong>×</strong><b>Rivais FC</b></div><p>Começou às 19:30 · opções de transmissão disponíveis</p></article><article className="event-card tennis"><span>HOJE · 21:00</span><small>TÊNIS · TORNEIO INTERNACIONAL</small><div className="teams"><b>Quadra Central</b><strong>×</strong><b>Semifinal</b></div><p>Acompanhe ao vivo pela MyTV.</p></article><article className="event-card schedule"><small>NA TV AGORA</small><h3>Filmes, notícias e muito mais.</h3><div className="progress"><i /></div><p>Confira a programação dos seus canais.</p></article></div></section>
  <section id="planos" className="plans section"><div className="section-heading centered"><p className="eyebrow">ESCOLHA SEU TEMPO</p><h2>Uma assinatura simples.</h2><p>Escolha o plano que funciona melhor para você. Sem fidelidade e com renovação prática.</p></div><div className="plan-grid">{plans.map(plan => <article className={`plan ${plan.featured ? 'featured' : ''}`} key={plan.name}>{plan.featured && <span className="best">MAIS ESCOLHIDO</span>}<h3>{plan.name}</h3><p>{plan.note}</p><div className="price"><sup>R$</sup><b>{plan.price}</b></div><small>acesso MyTV</small><button className={plan.featured ? 'primary' : 'outline'} onClick={() => setPortal(true)}>Escolher plano <span>→</span></button></article>)}</div></section>
  <section className="cta section"><div><p className="eyebrow">PRONTO PARA COMEÇAR?</p><h2>Sua próxima tela favorita<br />começa aqui.</h2></div><button className="primary" onClick={() => setPortal(true)}>Acessar minha conta <span>→</span></button></section>
  <footer><Brand /><p>© {new Date().getFullYear()} MyTV. Todos os direitos reservados.</p><div><a href="#">Termos</a><a href="#">Privacidade</a><a href="#">Suporte</a></div></footer></>
}

function Portal({ setPortal }) {
  const [tab, setTab] = useState('inicio'); const [notice, setNotice] = useState('')
  const action = (message) => { setNotice(message); setTimeout(() => setNotice(''), 3500) }
  return <main className="portal"><aside className="portal-side"><Brand /><div className="account"><span className="avatar large">A</span><div><b>Olá, Antonio</b><small>ID MyTV #41758333</small></div></div>{[['inicio','Visão geral'],['planos','Planos e renovação'],['dados','Meus dados'],['ajuda','Ajuda e suporte']].map(([id, label]) => <button key={id} className={tab === id ? 'selected' : ''} onClick={() => setTab(id)}><span>{id === 'inicio' ? '⌂' : id === 'planos' ? '◇' : id === 'dados' ? '◌' : '?'}</span>{label}</button>)}<button className="back" onClick={() => setPortal(false)}>← Voltar ao site</button></aside><section className="portal-main"><header><div><p className="eyebrow">MINHA CONTA</p><h1>{tab === 'inicio' ? 'Olá, Antonio.' : tab === 'planos' ? 'Planos e renovação' : tab === 'dados' ? 'Meus dados' : 'Estamos aqui para ajudar'}</h1></div><span className="avatar">A</span></header>{notice && <div className="toast">✓ {notice}</div>}{tab === 'inicio' && <><section className="status-card"><div><span className="active-dot">● Acesso ativo</span><h2>Seu acesso vai até<br /><em>30 de setembro.</em></h2><p>Renove antes do vencimento para continuar aproveitando.</p></div><button className="primary" onClick={() => setTab('planos')}>Renovar agora →</button></section><div className="account-grid"><article><small>PLANO ATUAL</small><h3>MyTV Trimestral</h3><p>3 telas simultâneas</p><button className="text-button" onClick={() => setTab('planos')}>Gerenciar plano →</button></article><article><small>PRÓXIMO VENCIMENTO</small><h3>30 set. 2026</h3><p>Faltam 3 dias</p><button className="text-button" onClick={() => setTab('planos')}>Renovar acesso →</button></article></div></>}{tab === 'planos' && <div className="portal-plans">{plans.map(plan => <article className={plan.featured ? 'featured' : ''} key={plan.name}><h3>{plan.name}</h3><p>{plan.note}</p><b>R$ {plan.price}</b><button className="primary" onClick={() => action(`Pedido de ${plan.name} iniciado. Escolha o PIX na próxima etapa.`)}>Renovar com PIX →</button></article>)}</div>}{tab === 'dados' && <form className="profile-form" onSubmit={(event) => { event.preventDefault(); action('Dados salvos com segurança.') }}><label>Nome<input defaultValue="Antonio" /></label><label>E-mail<input type="email" defaultValue="antonio@email.com" /></label><label>Telefone<input defaultValue="(00) 00000-0000" /></label><button className="primary">Salvar alterações →</button></form>}{tab === 'ajuda' && <section className="support-card"><h2>Precisa de ajuda?</h2><p>Fale com a equipe MyTV para tirar dúvidas sobre acesso, renovação ou sua TV.</p><button className="primary" onClick={() => action('O atendimento será aberto pelo WhatsApp.')}>Abrir atendimento →</button></section>}</section></main>
}

function App() { const [portal, setPortal] = useState(location.pathname.startsWith('/minha-conta')); return <><Header portal={portal} setPortal={setPortal} />{portal ? <Portal setPortal={setPortal} /> : <Landing setPortal={setPortal} />}</> }
createRoot(document.getElementById('root')).render(<App />)
